import tweepy
auth = tweepy.OAuthHandler("Type your consumer key here", "Type your consumer secret here") 
auth.set_access_token("Type your accedd token here", "Type your access token secret here")
api = tweepy.API(auth)
print("=============================")
print("Selamat Datang Dzaky Rifa'i")
print("=============================")
print("Mau Nge-Reply Apa Hari Ini?")
reply = input("Masukkan Disini: ")
print("Masukkan ID Statusnya")
tweetId = input("")
api.update_status(reply, in_reply_to_status_id = tweetId, auto_populate_reply_metadata=True)
print("=============================")
print ("Done!")
print("=============================")